Repository Winter-opp/Assignment2, pull requests merged in 2019-12, with the labels that each got.

#1 commit
  .gitignore
  .idea/description.html
  .idea/encodings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/project-template.xml
  .idea/vcs.xml
  src/com/company/Main.java
  teamproject.iml
Labels: review

#2 ui 구현
  src/com/company/Main.java
  src/controller/ProductController.java
  src/data/ProductDAO.java
  src/data/ProductDAOImpl.java
  src/data/dao/Product.java
  src/ui/AppMain.java
  src/ui/View.java
Labels: Conversation

#3 Controller Feature
  src/com/company/Main.java
  src/controller/ProductController.java
  src/data/ProductDAO.java
  src/data/ProductDAOImpl.java
  src/data/dao/Product.java
  src/ui/AppMain.java
  src/ui/View.java
Labels: review

#4 Create Model & Table
  src/com/company/Main.java
  src/data/ProductDAO.java
  src/data/ProductDAOImpl.java
  src/data/dao/Product.java
  src/ui/AppMain.java
  teamproject.iml
Labels: Conversation

#5 Add ComboBox Lists Request
  src/controller/ProductController.java
  src/data/ProductDAO.java
  src/data/ProductDAOImpl.java
  src/ui/AppMain.java
  src/ui/View.java
Labels: merge

#6 마지막 버그 수정!
  src/ui/AppMain.java
Labels: merge
